import type { Metadata } from "next";
import "./globals.css";
import { Dock } from "@/components/business/MyDock";
import LanguageSwitch from "@/components/business/LanguageSwitch";
import { Mainlogo } from "@/components/business/Logo";

// 网页标题
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="antialiased">
        {children}
        <LanguageSwitch />
        <Dock />
        <Mainlogo />
      </body>
    </html>
  );
}

